### ISSUE TITLE
[Bug] Missing YML in Test Report for Query Parameter Paths

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#5577]
In our recent cron-based smoke test jobs, we observed that for certain API paths containing a `?` (question mark), the test report fails to retrieve the corresponding component `.yml` file. As a result, the test status is incorrectly marked as `Not Available` in the report, even though the actual test cases have passed.

For example, in this [test report](https://build.ci.opensearch.org/job/smoke-test/350/artifact/test-report.yml/*view*/), the following entry appears:
```
- name: POST___bulk?refresh=true
  status: Not Available
  yml: URL not available
  test_stdout: https://ci.opensearch.org/.../POST___bulk?refresh=true/stdout.txt
  test_stderr: https://ci.opensearch.org/.../POST___bulk?refresh=true/stderr.txt
```
Although the report claims the `.yml` file is unavailable, the expected file (`ml-commons.yml`) does exist at this path:
[ml-commons.yml](https://ci.opensearch.org/ci/dbc/smoke-test/3.1.0/11165/linux/x64/deb/test-results/350/smoke-test/ml-commons/POST___bulk?refresh=true/ml-commons.yml)

We believe this issue stems from improper handling of special characters like `?` in the test spec paths — either in the report generation logic or during artifact upload.

I recommend improving the report workflow to:
- Properly URL-encode special characters like `?`, or
- Adjust the upload path to avoid using query parameters in directory names.

This would help ensure `.yml` files are consistently retrievable and accurately reflected in the final test report.

**Comment by gaiksaya** [comment]
[Triage] Hi @zelinh 
Is the issue coming from python or jenkins libraries? We have seen similar issues for jenkins library for `*` before where the encoding gets resolved to `%2A`

**Comment by prudhvigodithi** [comment]
Coming from similar issue in past https://github.com/opensearch-project/opensearch-build-libraries/issues/493#issuecomment-2635613358, running the post actions inside the docker agent should fix this error. We can try updating the https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/smoke-test.jenkinsfile#L147-L171 to use docker container.

**Comment by gaiksaya** [comment]
Looks like it is already running in the docker container https://build.ci.opensearch.org/view/Test/job/smoke-test/692/flowGraphTable/
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/smoke-test.jenkinsfile#L89-L168
Need to debug more.

**Comment by gaiksaya** [comment]
This is what the folder path looks like 

<img width="392" height="233" alt="Image" src="https://github.com/user-attachments/assets/888148ba-e8a8-4743-9322-f5fb00eb67a3" />

I believe not including query parameters in the folder structure is the way to move forward. Even the URLs that are added in the test report for stdout.txt are not reachable because of the `?` in the folder structure being mistaken for a query parameter for the URL.

**Comment by gaiksaya** [comment]
Re-opening this issue as `URL not available` issue still persists. See https://build.ci.opensearch.org/job/smoke-test/693/artifact/test-report.yml/*view*/

**Comment by gaiksaya** [comment]
No more unavailable URLs found: https://build.ci.opensearch.org/job/smoke-test/lastSuccessfulBuild/artifact/test-report.yml/*view*/
